permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

# 作者信息
author: 
  name: Lei Dan
  email: lilei8630@gmail.com
  link: http://58ideas.com
  github: https://github.com/lilei8630

# 站点信息
title: 雷丹的博客
description: My personal blog
url: http://58ideas.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: 58ideas.com

# disqus 设置
disqus:
  shortname: 58ideas

# 主题设置，自动激活某个标签
active: 技术
# 首页除了最新文章外显示分类
cates: 
  - Efficiency
  - Tips
#更改markdown引擎
markdown: kramdown
kramdown:
   input: GFM
   highlighter: rouge

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

gems: [jekyll-paginate,jekyll-pseudo]

# jekyll-scholar
scholar:
    style: assets/bibliography/ieee.csl
    locale: en
    
    sort_by: none
    order: descending
    bibliography_list_tag: ul
    
    source: _bibliography
    repository: pdf
    bibliography: references
    bibliography_template: bibliography

    replace_strings: true

    details_dir:    bibliography
    details_layout: bibtex.html
    details_link:   Details

    query: "@*"
    
